name: Sync and Merge Firefox Configs

on:
  workflow_dispatch:

  schedule:
    - cron: "0 12 * * *"

  push:
    branches:
      - master

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Sync chrome directory from gwfox
        run: |
          echo "Cloning gwfox repository sparsely for 'chrome' directory..."
          git clone --depth 1 --filter=blob:none --sparse https://github.com/akkva/gwfox.git ./tmp_gwfox
          cd ./tmp_gwfox
          git sparse-checkout set chrome
          cd ..

          echo "Replacing local chrome directory with the new one..."
          rm -rf ./chrome
          mv ./tmp_gwfox/chrome ./chrome
          rm -rf ./tmp_gwfox

      - name: Process user.js files with blocklist
        run: |
          echo "Fetching user.js files..."
          curl -sL "https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js" -o ./betterfox_user.js
          echo "Merging and de-duplicating..."
          cat ./betterfox_user.js ./user-overrides.js > ./merged_user.js

          awk -F'"' '/^user_pref\(/{prefs[$2]=$0} END{for(p in prefs)print prefs[p]}' ./merged_user.js | sort > ./user.js

          echo "Cleaning up temporary files..."
          rm ./betterfox_user.js ./merged_user.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Sync: Update Firefox configs"
          file_pattern: "user.js chrome/ user-overrides.js"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"
