name: Sync and Merge Firefox Configs

on:
  # 1. 允许你从 GitHub 仓库的 Actions 页面手动触发此工作流
  workflow_dispatch:

  # 2. 设置定时任务，每天 UTC 时间 11:00 运行一次
  schedule:
    - cron: '0 11 * * *'

  push:
    branches:
      - master

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    permissions:
      # 授予工作流向你的仓库写入内容的权限
      contents: write

    steps:
      # 第 1 步: 检出你自己的仓库，这样我们才能在里面工作和提交
      # 我们需要获取 user_private.js 文件，所以这次 checkout 很重要
      - name: Checkout self
        uses: actions/checkout@v4

      # 第 2 步: 同步 gwfox 的 chrome 目录 (此步骤不变)
      - name: Sync chrome directory from gwfox
        run: |
          echo "Cloning gwfox repository sparsely for 'chrome' directory..."
          git clone --depth 1 --filter=blob:none --sparse https://github.com/akkva/gwfox.git ./tmp_gwfox
          cd ./tmp_gwfox
          git sparse-checkout set chrome
          cd ..
          
          echo "Replacing local chrome directory with the new one..."
          rm -rf ./chrome
          mv ./tmp_gwfox/chrome ./chrome
          rm -rf ./tmp_gwfox

      # 第 3 步: 拉取、合并和处理 user.js 文件 (★★★ 这里有修改 ★★★)
      - name: Process user.js files
        run: |
          echo "Fetching user.js files..."
          curl -sL "https://raw.githubusercontent.com/akkva/gwfox/main/user.js" -o ./gwfox_user.js
          curl -sL "https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js" -o ./betterfox_user.js

          echo "Merging, stripping comments, and de-duplicating..."
          # ★★★ 修改点 ★★★
          # 将你自己的 user_private.js 文件放在合并顺序的最后
          # 这样你的设置就会覆盖掉 gwfox 和 Betterfox 中的任何同名设置
          cat ./gwfox_user.js ./betterfox_user.js ./user_private.js > ./merged_user.js

          # 核心处理步骤 (此部分不变)
          tac ./merged_user.js | grep '^user_pref' | awk -F '["()]' '!seen[$3]++' | tac > ./user.js

          echo "Cleaning up temporary files..."
          rm ./gwfox_user.js ./betterfox_user.js ./merged_user.js

      # 第 4 步: 提交变更 (此步骤不变)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Sync: Update Firefox configs"
          # 确保 file_pattern 也包含了你的 user_private.js 文件，以防它被错误删除
          file_pattern: "user.js chrome/ user_private.js"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"
